// Cross-language fixture generated by src/synths/dsp.py in the code repository.
// Run with Node, or import from the Codex Node runtime.
import { ExtendedKsaProcessor } from '../assets/js/interactive-ks.js';

const processor = new ExtendedKsaProcessor(16000, 233.08188075904496);
const output = new Float64Array(4096);
for (let n = 0; n < output.length; n += 1) {
  const excitation = n < 256 ? ((n * 37) % 101) / 50 - 1 : 0;
  output[n] = processor.process(excitation, {
    pluck: 0.22,
    dynamic: 0.62,
    damping: 0.34,
    decay: 0.994
  });
}

let sum = 0;
let sumSquares = 0;
let maximum = 0;
for (const sample of output) {
  sum += sample;
  sumSquares += sample * sample;
  maximum = Math.max(maximum, Math.abs(sample));
}

const expected = {
  sum: -0.002219455484140931,
  sumSquares: 35.670206423260616,
  maximum: 0.36242227977933156,
  indices: [0, 1, 17, 68, 69, 137, 511, 1023, 2047, 4095],
  samples: [-0.08976901087863165, -0.105050478392948, -0.0015248616891481992, 0.06602948488982903, -0.0672613279875871, -0.06439411833201251, 0.17515151168248994, 0.11270601941527411, 0.043758054103422137, -0.06495472902727639]
};

const close = (actual, reference, tolerance = 1e-11) => {
  if (Math.abs(actual - reference) > tolerance) throw new Error(`${actual} != ${reference}`);
};
close(sum, expected.sum);
close(sumSquares, expected.sumSquares);
close(maximum, expected.maximum);
expected.indices.forEach((index, i) => close(output[index], expected.samples[i]));

export const result = { sum, sumSquares, maximum };
